# Generated by Django 3.1.2 on 2021-06-22 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_usericon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='フォロした日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_user', to=settings.AUTH_USER_MODEL, verbose_name='フォロー元のユーザー')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_user', to=settings.AUTH_USER_MODEL, verbose_name='フォロー対象のユーザー')),
            ],
            options={
                'db_table': 'followuser',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_customuser_follow_+', through='users.FollowUser', to=settings.AUTH_USER_MODEL, verbose_name='フォロー'),
        ),
    ]
